version: '3.9'
services:
  file-service:
    build: .
    container_name: file-service
    restart: always
    networks:
      - internal
    ports:
      - 8080:8080
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - APPLICATION_ELASTICSEARCH_HOST=elasticsearch
      - APPLICATION_ELASTICSEARCH_PORT=9200
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elastic
    networks:
      - internal
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node

networks:
  internal: